### ISSUE TITLE
For issue #4 create Pull Request with separate branch

### ISSUE THREAD

**Issue by nrado** [matkopetar/the_shortest_path#5]
On major code refactoring it is easier to use `feature` branches and create pull request for merging them into `dvelop` / `master` branch.

**Comment by nrado** [comment]
on major code refactoring it is easier to use `feature` branches and create pull request for merging them into `dvelop` / `master` branch.

**Comment by matkopetar** [comment]
I have finished. Should I merge pull request I made?

**Comment by nrado** [comment]
Yes, merge (close) PR you made and close issues that you resolved.

Thnx.
